### PR TITLE
fix: support optional chaining operator

### PR DESCRIPTION
**Pull request by xiaoxiangmoe**

### CODE REVIEW

**Comment by xiaoxiangmoe** [comment]
@antfu We need also add optional call expression!

**Comment by moliyu** [comment]
@antfu it means optional chain can be used in template?

**Comment by xiaoxiangmoe** [comment]
@moliyu Yes. See https://github.com/xiaoxiangmoe/vue2-vuecli-demo

**Comment by moliyu** [comment]
> @moliyu Yes. See https://github.com/xiaoxiangmoe/vue2-vuecli-demo

Thanks，it works fine for me

**Pull request merged**
